### ISSUE TITLE
 Dynamic Movie/Show Images from TMDB Is not working for me

### ISSUE THREAD

**Issue by Bamboozul** [afonsojramos/discrakt#51]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

I'm not sure what I'm doing wrong, but the dynamic images are not working for me at all.

My credentials are as follows:

[Trakt API]
traktClientID = Client ID from trakt
traktUser = My trakt username

[Discord]
discordClientID = APPLICATION ID from discord

[TMDB API]
tmdbToken = API Key (v3 auth) from themoviedb

note:

I tried both API Key (v3 auth) and API Read Access Token (v4 auth) for tmdbToken

### 🪜 Steps To Reproduce

Fill up the credentials file and run the discrakt_win64.exe.

### ℹ System Info

```Markdown
Edition	Windows 11 Pro
Version	22H2
OS build	22621.1555
Experience	Windows Feature Experience Pack 1000.22640.1000.0
```

### 📸 Screenshots

![Screenshot 2023-05-08 223651](https://user-images.githubusercontent.com/101983929/236930819-bf04e32b-10b7-44c3-b476-60ef94c8c48b.png)

**Comment by afonsojramos** [comment]
Are you using a 2.2.5 or a version on your machine?

**Comment by afonsojramos** [comment]
@Bamboozul working on my end! Are you sure you're using the API Key (v3 auth)? Maybe I need to add something about that to the documentation....

**Comment by Bamboozul** [comment]
> @Bamboozul working on my end! Are you sure you're using the API Key (v3 auth)? Maybe I need to add something about that to the documentation....
> 
> Because locally it is working! <img alt="image" width="302" src="https://user-images.githubusercontent.com/19473034/240403536-85ace451-7c44-41e7-9071-b6fbad295a36.png">

Yes, I'm using API Key (v3 auth).

![Screenshot 2023-05-23 215822](https://github.com/afonsojramos/discrakt/assets/101983929/ca3cf568-8194-4ab6-b86b-727c580f32b1)
![Screenshot 2023-05-23 215550](https://github.com/afonsojramos/discrakt/assets/101983929/cd5c830c-18d1-4d12-8e2d-5ca2931001ba)

**Comment by vnnegt** [comment]
Not working for me either

**Comment by Manolo5678** [comment]
Same, Has anyone managed to solve it?

**Comment by vnnegt** [comment]
> Same, Has anyone managed to solve it?

na i'm assuming TMDB changed something on the backend

**Comment by Manolo5678** [comment]
@vnnegt  Well, seems like I need to learn Rust now then lol

**Comment by realtofuine** [comment]
@Manolo5678 
I recently made this: [PyDiscTrakt](https://github.com/realtofuine/PyDiscTrakt).

It's the same as this but in Python and the dynamic art does work. You can check it out and let me know if it works!

**Comment by afonsojramos** [comment]
> Same, Has anyone managed to solve it?

I think it is somehow related to the HTTP library I am using. But not entirely sure.

**Comment by realtofuine** [comment]
> > @Manolo5678 I recently made this: [PyDiscTrakt](https://github.com/realtofuine/PyDiscTrakt).
> > 
> > It's the same as this but in Python and the dynamic art does work. You can check it out and let me know if it works!
> > 
> > The config and everything is pretty much the same 😃
> 
> i can get it to run, but when i play content it starts to generate exceptions
> 
> i was watching the tv show `Fisk` and this exception popped up
> 
> ```
> Traceback (most recent call last):
>   File "traktdiscord.py", line 98, in <module>
> NameError: name 'movie' is not defined
> ```
> 

Uh oh, I'll look over it again and see.

**Comment by realtofuine** [comment]
> > @Manolo5678 I recently made this: [PyDiscTrakt](https://github.com/realtofuine/PyDiscTrakt).
> > It's the same as this but in Python and the dynamic art does work. You can check it out and let me know if it works!
> > The config and everything is pretty much the same 😃
> 
> i can get it to run, but when i play content it starts to generate exceptions
> 
> i was watching the tv show `Fisk` and this exception popped up
> 
> ```
> Traceback (most recent call last):
>   File "traktdiscord.py", line 98, in <module>
> NameError: name 'movie' is not defined
> ```

Ok, I fixed it is the latest release 1.0.1. I accidentally had deleted a line of code 😅.

You just need to download the exe or macOS file, just use the same config file and it should work now!

**Comment by realtofuine** [comment]
Sorry, this is also off-topic, but I was just wondering how you can find the time remaining in a movie or episode using the trakt api.

**Comment by vnnegt** [comment]
> > I think it is somehow related to the HTTP library I am using. But not entirely sure.
> 
> Idk what's going on, but I was able to fix it. I built my own .exe on Windows and everything worked fine on the first attempt, maybe there is something wrong with the .exe from the last release?

could you share the exe?

**Comment by vnnegt** [comment]
built my own exe and it's still not working for me

`https://www.themoviedb.org/settings/api/stats` doesn't show any requests - i've tried running the applications as admin as well

**Comment by thedinz** [comment]
> > > I think it is somehow related to the HTTP library I am using. But not entirely sure.
> > 
> > 
> > Idk what's going on, but I was able to fix it. I built my own .exe on Windows and everything worked fine on the first attempt, maybe there is something wrong with the .exe from the last release?
> 
> ~could you share the exe?~
> 
> nevermind, i figured it out.
> 
> you have to build with the latest source code from the repo itself - so either clone the repo or download the zip from the frontpage.
> 
> the zip files in the `Releases` section don't have the TMDB code. i stopped being lazy and opened up the source code i downloaded from the `Releases` section and observed that there were no references to TMDB at all.

How does one do that?

**Comment by afonsojramos** [comment]
Whoops, I guess I need to do a new release then 😅
